version: "3"

services:
  api-principal:
    build: ./api-principal
    environment:
      SECONDARY_API_URL: http://api-secundaria:8001
      SECONDARY_API_TIMEOUT: "30"
      SECONDARY_API_RETRIES: "1"
    ports:
      - "8000:8000"
    depends_on:
      - api-secundaria

  api-secundaria:
    build: ./api-secundaria
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api-principal